@startuml tvm-input-output-flow
title tvm input and output flow
(relay python frontend) as rpf

rectangle model-formats {
    (MXNet) -down-> rpf: relay.frontend.from_mxnet
    (TensorFlow) -down->rpf: relay.frontend.from_tensorflow
    (CoreML) -down->rpf: relay.frontend.from_coreml
    (ONNX) -down->rpf: relay.frontend.from_onnx
    (***) -down->rpf: relay.frontend.from_***
}

rpf -down-> (mod): output
note left: a object of tvm.relay.Module \nfor compilation 
rpf -down-> (params): output
note left: dict of str to NDArray \nInput parameters to the graph \nthat do not change during inference time. \nUsed for constant folding.
(mod) -down-> (func): mod[mod.entry_func]

(relay.build) as rb
(target) as target
note right: can be:\nllvm\ncuda\n...
target -left-> rb: input
(target_host) as th
note left: can be:cuda
th -> rb: input
(func) -down-> rb: input
(params) -down-> rb: input

rb -down-> (graph): output
rb -down-> (lib): output
rb -down-> (-params): output

(graph_runtime.create) as grc
(graph) -down-> grc: input
(lib) -down-> grc: input
(ctx: tvm.cpu0) -> grc: input

grc -down-> (runtime): output
(runtime.setinput) as rs
(-params) -down-> rs: input
(image data) -down-> rs: input
(runtime) -down-> rs: runtime method
(runtime.run) as rr
(runtime.getoutput) as rg
rs -> rr: runtime method
rr -> rg: runtime method

@enduml
